# This file is part of the BenGorFile package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    bengor.file.form.type.file:
        class: BenGorFile\FileBundle\Form\Type\FileType
        arguments:
            - '@bengor_file.file.command_bus'
            - '@bengor_file.file.repository'
        tags:
            - { name: form.type }


# ESTO HAY QUE PASARLO A UN COMPILER PASS
# ARREGLAR LOS SPECS
# A PARTIR DE LOS EJEMPLOS QUE TIENES FUNCIONANDO HACER LA DOCU DE "USAGE"
