# This file is part of the BenGorFile package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    bengor.file_bundle.routing.download_routes_loader:
        class: BenGorFile\FileBundle\Routing\DownloadRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }

    bengor.file_bundle.routing.api_get_files_routes_loader:
        class: BenGorFile\FileBundle\Routing\Api\GetFilesRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }

    bengor.file_bundle.routing.api_upload_routes_loader:
        class: BenGorFile\FileBundle\Routing\Api\UploadRoutesLoader
        arguments:
            - []
        public: false
        tags:
            - { name: routing.loader }
