# This file is part of the BenGorFile package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

bengor_file_get_file_api_routes:
    resource: .
    type: bengor_file_get_file_api
