# This file is part of the BenGorFileBundle bundle.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

bengor_file_upload:
    path: /upload
    defaults: { _controller: BenGorFileBundle:Upload:nonAjax }
    methods: [GET, POST]

bengor_file_upload_ajax:
    path: /ajax/upload
    defaults: { _controller: BenGorFileBundle:Upload:ajax }
    methods: [POST]
