# This file is part of the BenGorFileBundle bundle.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

bengor_upload:
    resource: upload.yml

bengor_overwrite:
    resource: overwrite.yml

bengor_remove:
    resource: remove.yml
